# pyproject.toml
[build-system]
requires = ["setuptools>=68", "wheel"] 
build-backend = "setuptools.build_meta"

[project]
name = "microjax"
version = "0.1.0"            
description = "Differentiable, GPU-accelerated microlensing modelling Framework in JAX"
readme = {file = "README.md", content-type = "text/markdown"}
license = {text = "MIT"}
authors = [
  {name="Shota Miyazaki", email="miyazaki@ir.isas.jaxa.jp"}
]
requires-python = ">=3.10"

dependencies = [
  "jax>=0.6.0",         
  "numpy>=1.26"
  "numpyro>=0.18.0"
]

[project.optional-dependencies]
dev   = ["black", "ruff", "pytest", "build", "twine"]
test  = ["pytest"]
cuda12 = ["jaxlib[cuda12]>=0.4"]

[project.urls]
Homepage      = "https://github.com/ShotaMiyazaki94/microjax"
Source        = "https://github.com/ShotaMiyazaki94/microjax"
Issues        = "https://github.com/ShotaMiyazaki94/microjax/issues"
Documentation = "https://github.com/ShotaMiyazaki94/microjax#readme"

[tool.setuptools]
package-dir = {"" = "src"}
[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*", "docs*"]
